### ISSUE TITLE
Doesn't seem to work with Chrome Releases Blog

### ISSUE THREAD

**Issue by chromestrong** [jdw353/g-suite-apps-script-toolbox#1]
If you changes the values to the following:

var FEEDS = {
  GSU: {
    format: FeedFormat.XML,
    title: 'Chrome Releases',
    subtitle: 'chromereleases.googleblog.com',
    source: 'https://chromereleases.googleblog.com/feeds/posts/default',
    logo: 'https://storage.googleapis.com/kimberlybucket001/chrome.png',
    cta: 'READ MORE',
    filters: ['Update'],
    webhooks: [WEBHOOKS.ADMIN_ROOM]
  },
};

The code almost works for the Chrome releases blog.  You will get updates but it fails when you click on the "READ MORE" button.  You don't get directed to the Blog instead you get redirected to the blogger feed.

**Comment by chromestrong** [comment]
Workaround:

var ALT_WEB = 'http://chromereleases.googleblog.com';

function buildHangoutsChatView_(feed, update) {
  return {
    'cards': [{
      'header': {
        'title': feed.title,
        'subtitle': feed.subtitle,
        'imageUrl': feed.logo,
      },
      'sections': [
        {
          'widgets': [
            {'textParagraph': {'text': '<b>' + update.title + '</b>'}},
            {'textParagraph': {'text': update.content}}
          ]
        },
        {
          'widgets': [{
            'buttons': [{
              'textButton': {
                'text': feed.cta,
                'onClick': {'openLink': {'url': ALT_WEB}}
              }
            }]
          }]
        }
      ]
    }]
  };
}

**Comment by jdw353** [comment]
Hi @chromestrong:

Thanks for pointing this out. I've added support for this blog in a more generic way in the following [commit](https://github.com/jdw353/g-suite-apps-script-toolbox/commit/cb543ddcf17671bc1e3a692084914c123df309d8).

Cheers,

Justin
